definitions:
  models.ConvoMessage:
    properties:
      content:
        type: string
      role:
        type: string
      timestamp:
        type: string
    type: object
host: gobot-backend-ew7jmfmn3a-uw.a.run.app
info:
  contact:
    name: Artur Shad Nik
  title: Gen AI capture the flag with Go
  version: "1.0"
paths:
  /chat/{id}:
    get:
      consumes:
      - application/json
      description: handler to fetch all past messages between the user and the bot
      parameters:
      - description: Difficulty Level
        in: query
        name: level
        required: true
        type: string
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get messages
      tags:
      - chat
    post:
      consumes:
      - application/json
      description: Get a response to a question
      parameters:
      - description: Message
        in: query
        name: message
        required: true
        type: string
      - description: Difficulty Level
        in: query
        name: level
        required: true
        type: string
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConvoMessage'
        "500":
          description: Internal Server Error
      summary: Chat with a bot
      tags:
      - chat
swagger: "2.0"
