definitions:
  models.Message:
    properties:
      body:
        example: Hello my name is Artur
        type: string
      name:
        example: gobot
        type: string
      timestamp:
        example: "2022-01-01T00:00:00Z"
        type: string
      uuid:
        example: 1
        type: integer
    type: object
info:
  contact: {}
  title: AI chatbot with Go
  version: "1.0"
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: Get a response to a question
      parameters:
      - description: Message request
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Chat with a bot
      tags:
      - chat
  /messages/{id}:
    get:
      consumes:
      - application/json
      description: handler to fetch all past messages between the user and the bot
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get messages
      tags:
      - chat
  /query:
    get:
      consumes:
      - application/json
      description: example for handling a request with a query
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: handle query
      tags:
      - chat
swagger: "2.0"
